linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15
  mnd:
    # don't include the "operation" and "assign"
    # checks: argument,case,condition,return
  gosec:
    severity: medium
    excludes:
      - G115
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gci:
    custom-order: true                   # enable sections-based sorting
    sections:
      - standard                         # stdlib
      - default                          # other
      - prefix(github.com/runZeroInc)    # us, case sensitive
    skip-generated: true
  lll:
    line-length: 250
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: unused-receiver
        disabled: true

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - gosec
    - govet
    - bodyclose
    - typecheck
    - unconvert
    - goprintffuncname
    - govet
    - ineffassign
    - noctx
    - asciicheck
    - rowserrcheck
    - revive

    # Deliberately not enabled:
    # - gci # is a more configurable import sorter than gofumpt
    # - nakedret # Disabled for now
    # - prealloc # Disabled for now
    # - nolintlint # Disabled for now
    # - unused # Crashes on netip package
    # - gofmt # Crashes on mapcidr/cidr.go
    # - goimports # Crashes on tcp_checkmk.go timestamp strings
    # - gosimple # Crashes on netip package
    # - staticcheck # Triggers OOM and takes forever to run

issues:
  include:
    - EXC0008
  exclude-use-default: false
  exclude-rules:
    - path: _test.go$
      linters:
        - lll
        - funlen
        - dupword
        - goconst
        - contextcheck
        - errorlint
        - testableexamples
        - forcetypeassert

    # Generated code
    - path: lib/proto/
      linters:
        - lll
        - gocritic
        - dupword
        - forcetypeassert
    - path: lib/devices/list.go
      linters:
        - lll
    - path: lib/js/helper.go
      linters:
        - lll

    - path: /fixtures/
      linters:
        - forbidigo

    - path: lib/examples/
      linters:
        - forbidigo
        - noctx
        - gocritic

    - path: examples?_test.go$
      linters:
        - forbidigo
        - noctx
        - gocritic

    - path: main.go$
      linters:
        - forbidigo
        - noctx
        - forcetypeassert
        - lll

    - path: lib/assets/
      linters:
        - lll


    # govet's shadow check can be useful, but redeclaring err and ctx is common. Annoying to work around linter.
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]

  exclude: